- hosts: web
  tasks:
  - name: Configure Docker repository
    yum_repository:
      name: docker
      description: docker Repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no

  - name: Install Docker..
    package:
      name:
            - "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: start docker services
    service:
      name: "docker"
      state: started
      enabled: yes


  - name: install python
    command: yum install python36 -y
  - name: docker sdk
    command: pip3 install docker


  - name: allowing firewall
    firewalld:
     masquerade: yes
     permanent: yes
     state: enabled
  - name: allow port 9898
    firewalld:
     port: "9898/tcp"
     permanent: yes
     state: enabled
  - name: restarting firewall
    service:
     name: "firewalld"
     state: restarted
  - name: restarting docker services
    service:
     name: "docker"
     state: restarted

  - name: Create a Folder For Our WebPages
    file:
      path: /web
      state: directory

  - name: copy web_pages
    copy:
      src: "/root/ansible_task1/server.html"
      dest: "/web/"

  - name: launch container using httpd image
    docker_container:
      name: webserver_ondocker
      image: httpd
      state: started
      exposed_ports:
      - "80"
      ports:
      - "9898:80"
      volumes:
      - /web:/usr/local/apache2/htdocs/
